### ISSUE TITLE
IP Submission

### ISSUE THREAD

**Issue by LatashaWanjira** [memetibryan/word-count-ruby#1]
You have done a good job though you need to ensure you indent your code properly and remove code that is not being used.
Make sure you add comments to the code to briefly explain what a section of code is doing.
Have more tests for your code, one is not enough.
Also make commits as often as possible, 30 per day.

**Comment by memetibryan** [comment]
Corrected my code and did the reviews asked. Thanks for outlining that

**Comment by memetibryan** [comment]
Corrected my code and did the reviews asked. Thanks for outlining that
